# Generated by Django 4.0.4 on 2022-05-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
