# Generated by Django 4.0.4 on 2022-05-06 00:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_remove_album_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='song',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
