# Generated by Django 4.0.4 on 2022-05-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_remove_album_song_album_songs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='album',
            name='songs',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
