# Generated by Django 4.0.4 on 2022-05-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_rename_created_album_created_at_alter_album_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='created_at',
        ),
    ]
